# Generated by Django 4.0.2 on 2022-06-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_purchase_alter_saleproducts_options_purchaseproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproducts',
            old_name='buy_price',
            new_name='buy',
        ),
    ]
