# Generated by Django 4.0.2 on 2022-06-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_buy_price_products_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproducts',
            old_name='sale',
            new_name='purchase',
        ),
    ]
