# Generated by Django 4.0.2 on 2022-06-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_sale_purchaseproducts_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_fk', to='store.products'),
        ),
    ]
