# Generated by Django 4.0.2 on 2022-06-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.employee'),
        ),
        migrations.AddField(
            model_name='sales',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to='store.road'),
        ),
        migrations.AddField(
            model_name='sales',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryman', to='store.employee'),
        ),
    ]
