# Generated by Django 4.0.2 on 2022-06-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_saleproducts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproducts',
            name='category',
        ),
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_fk', to='store.category'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_fk', to='store.employee'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_fk', to='store.road'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryman_fk', to='store.employee'),
        ),
    ]
