# Generated by Django 4.0.2 on 2022-06-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_saleproducts_category_sales_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tendered',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
