# Generated by Django 4.0.2 on 2022-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_purchase_tendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tendered',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
