# Generated by Django 4.0.2 on 2022-06-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_purchase_tendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tendered',
        ),
    ]
