# Generated by Django 4.0.2 on 2022-08-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_client_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='damage_quantity',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='good_quantity',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='sign',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
