# Generated by Django 4.0.2 on 2022-08-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_salereturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.FloatField(default=0, max_length=15)),
                ('paid', models.FloatField(default=0, max_length=15)),
                ('balance', models.FloatField(default=0, max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_fk', to='store.client')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_fk4', to='store.sales')),
            ],
            options={
                'verbose_name_plural': 'List of Sale Due',
            },
        ),
    ]
