# Generated by Django 4.0.2 on 2022-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_saledue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cost',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='sales',
            name='display_commission',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='sales',
            name='extra',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='sales',
            name='general_commission',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
