# Generated by Django 4.0.2 on 2022-08-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sales_cost_sales_display_commission_sales_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
