# Generated by Django 4.0.2 on 2022-08-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_products_brand_products_code_products_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=0, max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk', to='store.brand')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_fk5', to='store.sales')),
            ],
            options={
                'verbose_name_plural': 'List of Sale Commission',
            },
        ),
    ]
