# Generated by Django 4.0.2 on 2022-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_salecommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecommission',
            name='total_amount',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
