# Generated by Django 4.0.2 on 2022-08-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_salecommission_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='display_commission',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='general_commission',
        ),
        migrations.AddField(
            model_name='saledue',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk', to='store.brand'),
        ),
        migrations.AlterField(
            model_name='salecommission',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk2', to='store.brand'),
        ),
    ]
