# Generated by Django 4.0.2 on 2022-08-20 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_sales_display_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecommission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
