# Generated by Django 4.0.2 on 2022-08-20 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_salecommission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecommission',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
