# Generated by Django 4.0.2 on 2022-08-21 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_salecommission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=12)),
                ('bill', models.FloatField(default=0, max_length=15)),
                ('collect', models.FloatField(default=0, max_length=15)),
                ('due', models.FloatField(default=0, max_length=15)),
                ('total_balance', models.FloatField(default=0, max_length=15)),
                ('status', models.CharField(choices=[('1', 'Unpaid'), ('2', 'Paid')], default=1, max_length=2)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
            options={
                'verbose_name_plural': 'List of Commission Bills',
            },
        ),
    ]
