# Generated by Django 4.0.2 on 2022-08-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_commissionbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionbill',
            name='due',
        ),
        migrations.RemoveField(
            model_name='commissionbill',
            name='total_balance',
        ),
    ]
