# Generated by Django 4.0.2 on 2022-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_commissionbill_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionbill',
            name='due',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='commissionbill',
            name='total_balance',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
