# Generated by Django 4.0.2 on 2022-08-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_commissionbill_due_commissionbill_total_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionbill',
            name='due',
        ),
        migrations.RemoveField(
            model_name='commissionbill',
            name='total_balance',
        ),
    ]
