# Generated by Django 4.0.2 on 2022-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_commissionbill_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledue',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
