# Generated by Django 4.0.2 on 2022-08-22 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_saledue_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
