# Generated by Django 4.0.2 on 2022-08-23 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_saleproducts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'In-progress'), ('2', 'Done')], default=0, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Advance',
            },
        ),
        migrations.CreateModel(
            name='AdvanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.FloatField(default=0, max_length=15)),
                ('receive', models.FloatField(default=0, max_length=15)),
                ('total_due', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_fk', to='store.advance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fk2', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'List of Advance Group',
            },
        ),
    ]
