# Generated by Django 4.0.2 on 2022-08-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_advance_advancegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancegroup',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='advancegroup',
            name='category',
        ),
        migrations.DeleteModel(
            name='Advance',
        ),
        migrations.DeleteModel(
            name='AdvanceGroup',
        ),
    ]
