# Generated by Django 4.0.2 on 2022-08-23 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_advancegroup_advance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'In-progress'), ('2', 'Done')], default=0, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Advance',
            },
        ),
        migrations.CreateModel(
            name='OnlineAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.FloatField(default=0, max_length=15)),
                ('receive', models.FloatField(default=0, max_length=15)),
                ('due', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk3', to='store.brand')),
                ('online', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_fk', to='store.online')),
            ],
            options={
                'verbose_name_plural': 'List of Advance Brand',
            },
        ),
    ]
