# Generated by Django 4.0.2 on 2022-08-25 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_expense_surplus_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
