# Generated by Django 4.0.2 on 2022-08-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_saleproducts_brand_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
    ]
