# Generated by Django 4.0.2 on 2022-08-25 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_saleproducts_brand_remove_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
