# Generated by Django 4.0.2 on 2022-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
