# Generated by Django 4.0.2 on 2022-08-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_saleproducts_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='category',
        ),
        migrations.AddField(
            model_name='sales',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_fk', to='store.brand'),
        ),
    ]
