# Generated by Django 4.0.2 on 2022-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_sales_category_sales_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='saledue',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
