# Generated by Django 4.0.2 on 2022-08-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_surplus_total_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
