# Generated by Django 4.0.2 on 2022-08-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_credit_debit_loan_alter_charge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandebit',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_fk', to='store.debit'),
        ),
    ]
