# Generated by Django 4.0.2 on 2022-09-01 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_loandebit_debit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineadvance',
            old_name='due',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='onlineadvance',
            name='receive',
        ),
        migrations.AddField(
            model_name='online',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='online',
            name='due_amount',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='OnlineCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk4', to='store.brand')),
                ('online', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_fk2', to='store.online')),
            ],
            options={
                'verbose_name_plural': 'List of Loans Credited',
            },
        ),
    ]
