# Generated by Django 4.0.2 on 2022-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_onlinecredit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadvance',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
