# Generated by Django 4.0.2 on 2022-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_onlineadvance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancredit',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loandebit',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinecredit',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
