# Generated by Django 4.0.2 on 2022-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_loancredit_day_loandebit_day_onlinecredit_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
