# Generated by Django 4.0.2 on 2022-09-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_remove_purchase_client_remove_purchase_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_fk6', to='store.brand'),
        ),
        migrations.AddField(
            model_name='online',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
