# Generated by Django 4.0.2 on 2022-09-07 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_online_brand_online_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('due_amount', models.FloatField(max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'List of Expenditure',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('1', 'Salesman'), ('2', 'Deliveryman'), ('3', 'Manager'), ('4', 'AIC')], default=1, max_length=2),
        ),
        migrations.CreateModel(
            name='ExpenditureCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(max_length=100)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_fk', to='store.surplus')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_fk2', to='store.expense')),
            ],
            options={
                'verbose_name_plural': 'List of Expenditure Charges',
            },
        ),
    ]
