# Generated by Django 4.0.2 on 2022-09-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_expenditure_alter_employee_type_expenditurecharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='due_amount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='expenditurecharge',
            name='expenditure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_fk', to='store.expenditure'),
        ),
    ]
