# Generated by Django 4.0.2 on 2022-09-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_rename_due_amount_expenditure_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_fk', to='store.products'),
        ),
    ]
