# Generated by Django 4.0.2 on 2022-09-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_bank_banktransaction_investment_onlinetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.FloatField(default=0, max_length=15)),
                ('balance', models.FloatField(default=0, max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_fk2', to='store.client')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_fk6', to='store.sales')),
            ],
            options={
                'verbose_name_plural': 'List of Sale Collect',
            },
        ),
    ]
