# Generated by Django 4.0.2 on 2022-09-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_salecollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledue',
            name='new',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='saledue',
            name='previous',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
