# Generated by Django 4.0.2 on 2022-09-13 05:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_delete_salecollect'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledue',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='saledue',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='saledue',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
