# Generated by Django 4.0.2 on 2022-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_alter_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagesale',
            name='paid_amount',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damagesale',
            name='payable_amount',
            field=models.FloatField(default=0.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damagesale',
            name='short',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
