# Generated by Django 4.0.2 on 2022-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_damagesale_paid_amount_damagesale_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='damagesale',
            name='payable_amount',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
