# Generated by Django 4.0.2 on 2022-11-14 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_purchase_note_alter_damagesale_payable_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=12)),
                ('total_amount', models.FloatField(max_length=15)),
                ('extra', models.FloatField(default=0, max_length=15)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Due'), ('2', 'Done')], default=0, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_fk7', to='store.brand')),
            ],
            options={
                'verbose_name_plural': 'List of Discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk9', to='store.brand')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_fk2', to='store.discount')),
            ],
            options={
                'verbose_name_plural': 'List of Discount Received',
            },
        ),
        migrations.CreateModel(
            name='DiscountGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.FloatField(default=0, max_length=15)),
                ('price', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brand_fk8', to='store.brand')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_fk', to='store.discount')),
            ],
            options={
                'verbose_name_plural': 'List of Discount Given',
            },
        ),
        migrations.CreateModel(
            name='DiscountDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_fk10', to='store.brand')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_fk3', to='store.discount')),
            ],
            options={
                'verbose_name_plural': 'List of Discount Due',
            },
        ),
    ]
