# Generated by Django 4.0.2 on 2022-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_discount_discountreceived_discountgiven_discountdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineadvance',
            name='previous',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
