from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',views.home, name="home-page"),
    path('login',views.login_page,name='login-page'),
    path('register',views.userregister,name='register-page'),
    path('save_register',views.save_register,name='register-user'),
    path('user_login',views.login_user,name='login-user'),
    path('home',views.home,name='home-page'),
    path('logout',views.logout_user,name='logout'),
    path('profile',views.profile,name='profile-page'),
    path('update_password',views.update_password,name='update-password'),
    path('update_profile',views.update_profile,name='update-profile'),
    path('users',views.users,name='user-page'),
    path('manage_user',views.manage_user,name='manage-user'),
    path('manage_user/<int:pk>',views.manage_user,name='manage-user-pk'),
    path('save_user',views.save_user,name='save-user'),
    path('delete_user/<int:pk>',views.delete_user,name='delete-user'),
    path('category',views.category,name='category-page'),
    path('manage_category',views.manage_category,name='manage-category'),
    path('manage_category/<int:pk>',views.manage_category,name='manage-category-pk'),
    path('view_category/<int:pk>',views.view_category,name='view-category-pk'),
    path('save_category',views.save_category,name='save-category'),
    path('delete_category/<int:pk>',views.delete_category,name='delete-category'),
    path('products',views.products,name='product-page'),
    path('manage_product',views.manage_product,name='manage-product'),
    path('manage_product/<int:pk>',views.manage_product,name='manage-product-pk'),
    path('view_product',views.view_product,name='view-product'),
    path('view_product/<int:pk>',views.view_product,name='view-product-pk'),
    path('save_product',views.save_product,name='save-product'),
    path('delete_product/<int:pk>',views.delete_product,name='delete-product'),
    path('manage_stockin/<int:pid>',views.manage_stockin,name='manage-stockin-pid'),
    path('manage_stockin/<int:pid>/<int:pk>',views.manage_stockin,name='manage-stockin-pid-pk'),
    path('save_stockin',views.save_stockin,name='save-stockin'),
    path('delete_stockin/<int:pk>',views.delete_stockin,name='delete-stockin'),
    path('sales',views.sales,name='sale-page'),
    path('manage_sale',views.manage_sale,name='manage-sale'),
    path('manage_sale/<int:pk>',views.manage_sale,name='manage-sale-pk'),
    path('view_sale',views.view_sale,name='view-sale'),
    path('view_sale/<int:pk>',views.view_sale,name='view-sale-pk'),
    path('save_sale',views.save_sale,name='save-sale'),
    path('delete_sale/<int:pk>',views.delete_sale,name='delete-sale'),
    path('update_transaction_form/<int:pk>',views.update_transaction_form,name='transacton-update-status'),
    path('update_transaction_status',views.update_transaction_status,name='update-sale-status'),
    path('daily_report',views.daily_report,name='daily-report'),
    path('daily_report/<str:date>',views.daily_report,name='daily-report-date'),
    path('purchase',views.purchase,name='purchase-page'),
    path('manage_purchase',views.manage_purchase,name='manage-purchase'),
    path('manage_purchase/<int:pk>',views.manage_purchase,name='manage-purchase-pk'),
    path('view_purchase',views.view_purchase,name='view-purchase'),
    path('view_purchase/<int:pk>',views.view_purchase,name='view-purchase-pk'),
    path('save_purchase',views.save_purchase,name='save-purchase'),
    path('delete_purchase/<int:pk>',views.delete_purchase,name='delete-purchase'),
    path('update_receipt_form/<int:pk>',views.update_receipt_form,name='receipt-update-status'),
    path('update_receipt_status',views.update_receipt_status,name='update-purchase-status'),
    path('employee',views.employee,name='employee-page'),
    path('manage_employee',views.manage_employee,name='manage-employee'),
    path('manage_employee/<int:pk>',views.manage_employee,name='manage-employee-pk'),
    path('save_employee',views.save_employee,name='save-employee'),
    path('delete_employee/<int:pk>',views.delete_employee,name='delete-employee'),
    path('road',views.road,name='road-page'),
    path('manage_road',views.manage_road,name='manage-road'),
    path('manage_road/<int:pk>',views.manage_road,name='manage-road-pk'),
    path('save_road',views.save_road,name='save-road'),
    path('delete_road/<int:pk>',views.delete_road,name='delete-road'),
    path('print-sales/<id>', views.print_sales, name='print-sales'),
    path('ajax/load-product/', views.load_product, name='ajax_load_product'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)